### PR TITLE
Fixed compilation bug on macOS

### PR DESCRIPTION
**Pull request by yoav-orca**
fixes - https://github.com/googleprojectzero/TinyInst/issues/20

I'm also adding a sanity build support for TinyInst, this doesn't create build artifacts (we had this discussion on WinAFL).
But it will make sure that this project continues to build on all platforms (2 macOS versions & windows-2019)

### CODE REVIEW

**Comment by yoav-orca** [comment]
@googlebot I signed it!

**Comment by ifratric** [comment]
Hi Yoav,
Thanks for the PR!

Would you mind breaking this into 2 PRs?

I'd like to fix the compile issue ASAP.

I think the second part is also good, but I'd like to wait until I come back from my vacation in early January, I'll need to figure out which organization tier we'd need to use github actions first.

**Comment by yoav-orca** [comment]
Hi Ivan,

I'll split the PRs, AFAIK Github actions are free for open source projects within very reasonable limits (2000 actions minutes, divided by 3 minutes for all 3 runners should be ~660 builds a month)

Have fun on your vacation!

**Comment by ifratric** [comment]
Thanks Yoav!

For the actions: That indeed sounds like it should be more than sufficient, but I'll still wait to be back in the "office" before merging, on account of not being very familiar with github actions. On a chance that I forget, feel free to ping the other PR.

**Pull request merged**
